-- select * from cleaned_customer_shopping_behavior;

-- Q1 WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?  
select gender , sum(purchase_amount) as revenue
from cleaned_customer_shopping_behavior
group by gender;

-- Q2 WHICH CUSTOMER USED THE DISCOUNT CODE BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
select customer_id , purchase_amount as purchase_amount ,(select avg(purchase_amount) from cleaned_customer_shopping_behavior) as avg_purchase_amount
from cleaned_customer_shopping_behavior
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from cleaned_customer_shopping_behavior);
 
-- Q3 WHICH ARE THE TOP 5 PRODUCTS WITH HIGHEST AVERAGE REVIEW RATING
 select item_purchased, round(avg(review_rating),2) as "average product rating"
 from cleaned_customer_shopping_behavior
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;
 
 -- Q4 COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD AND EXPRESS SHIPPING?
 select shipping_type , round(avg(purchase_amount),2) as 'avg shipping charges'
 from cleaned_customer_shopping_behavior
 where shipping_type in ('standard','express')
 group by shipping_type;
 
 -- Q5. Do subscribed customers spend more? aveage spend and total revenue between subscribers and non-subscribers.
	select subscription_status,
	count(customer_id) as total_customers,
	round(avg(purchase_amount),2) as average_purchase_amount,
    round(sum(purchase_amount),2) as total_revenue
    from cleaned_customer_shopping_behavior
    group by subscription_status;
    
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from cleaned_customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id , previous_purchases,
case
	when previous_purchases = 1 then 'new'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal' 
    end as customer_segment
from cleaned_customer_shopping_behavior)

select customer_segment, count(*) as 'number of customers'
from customer_type
group by customer_segment;

-- Q8 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers
from cleaned_customer_shopping_behavior
where previous_purchases > 5
group by subscription_status; 

-- Q9 What is the revenue contribution of each age group?
select age_group , sum(purchase_amount) as total_revenue
from cleaned_customer_shopping_behavior
group by age_group 
order by total_revenue desc;